//! Deterministic, documentation-only design analysis built from the canonical
//! Excel object-model records. This module never edits `data/`.

use crate::model::{MemberRecord, ObjectRecord, RelationshipRecord, SourceCoverage};
use crate::validate;
use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

const REPORTS: [&str; 6] = [
    "architectural-spine.md",
    "candidate-0.1-members.md",
    "collection-analysis.md",
    "optional-argument-targets.md",
    "typelib-audit-targets.md",
    "runtime-probe-targets.md",
];

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AnalysisSummary {
    pub reports: usize,
}

pub fn analyze_reports(root: &Path) -> Result<AnalysisSummary, String> {
    validate::validate_root(root)?;
    let reports = report_contents(root)?;
    let directory = root.join("generated").join("analysis");
    fs::create_dir_all(&directory)
        .map_err(|error| format!("cannot create {}: {error}", directory.display()))?;
    for (name, content) in reports {
        fs::write(directory.join(name), content)
            .map_err(|error| format!("cannot write analysis report: {error}"))?;
    }
    Ok(AnalysisSummary {
        reports: REPORTS.len(),
    })
}

pub fn check_reports(root: &Path) -> Result<(), String> {
    let first = report_contents(root)?;
    let second = report_contents(root)?;
    if first != second {
        return Err("analysis report generation is not deterministic".to_owned());
    }
    for (name, expected) in first {
        let path = root.join("generated").join("analysis").join(name);
        let actual = fs::read_to_string(&path)
            .map_err(|error| format!("cannot read analysis report {}: {error}", path.display()))?;
        if actual != expected {
            return Err(format!(
                "analysis report {} is stale; run analyze",
                path.display()
            ));
        }
        if actual.contains("\r\n") || !actual.ends_with('\n') {
            return Err(format!(
                "analysis report {} does not use deterministic LF/final-newline output",
                path.display()
            ));
        }
    }
    Ok(())
}

pub fn report_contents(root: &Path) -> Result<BTreeMap<&'static str, String>, String> {
    let (objects, members, relationships, _enums, coverage) = validate::load_records(root)?;
    let mut reports = BTreeMap::new();
    reports.insert(
        "architectural-spine.md",
        architectural_spine(&objects, &members, &relationships, &coverage),
    );
    reports.insert("candidate-0.1-members.md", candidate_members(&members));
    reports.insert(
        "collection-analysis.md",
        collection_analysis(&objects, &members, &coverage),
    );
    reports.insert(
        "optional-argument-targets.md",
        optional_targets(&members, &relationships),
    );
    reports.insert("typelib-audit-targets.md", typelib_targets(&members));
    reports.insert("runtime-probe-targets.md", runtime_probes(&members));
    Ok(reports)
}

fn heading(title: &str, purpose: &str) -> String {
    format!(
        "# {title}\n\nGenerated by `excel-com-kb analyze`; do not edit by hand. {purpose}\n\nEvidence labels are deliberate: **Documentation-established** is extracted from the pinned VBA documentation; **Project classification** is a planning label; **Type-library verification required** and **Runtime verification required** are open gates. No production API, COM activation, or type-library inspection is performed.\n\n"
    )
}

fn architectural_spine(
    objects: &[ObjectRecord],
    members: &[MemberRecord],
    relationships: &[RelationshipRecord],
    coverage: &SourceCoverage,
) -> String {
    let mut output = heading(
        "Excel Automation architectural spine",
        "This is a documentation-derived navigation inventory, not an API commitment.",
    );
    output.push_str("## Baseline\n\n");
    output.push_str(&format!(
        "Documentation-established: the pinned corpus selected **{}** files and parsed **{}**; this analysis reads {} objects, {} members, and {} relationships.\n\n",
        coverage.selected_files,
        coverage.parsed_files,
        objects.len(),
        members.len(),
        relationships.len()
    ));
    output.push_str("## Root candidates\n\n| Candidate | Canonical evidence | Planning status |\n| --- | --- | --- |\n");
    for id in [
        "Excel.Application.Visible",
        "Excel.Application.Version",
        "Excel.Application.Workbooks",
        "Excel.Application.ActiveWorkbook",
        "Excel.Application.ActiveSheet",
        "Excel.Application.Calculation",
        "Excel.Application.DisplayAlerts",
        "Excel.Application.ScreenUpdating",
        "Excel.Application.EnableEvents",
        "Excel.Application.Run",
        "Excel.Application.Quit",
    ] {
        output.push_str(&format!(
            "| `{id}` | {} | Project classification: candidate only; Type-library verification required; Runtime verification required. |\n",
            member_evidence(members, id)
        ));
    }
    output.push_str("\n## Spine objects\n\n| Object | Role | Canonical source evidence | Gate |\n| --- | --- | --- | --- |\n");
    for (id, role) in [
        ("Excel.Application", "Automation root"),
        ("Excel.Workbooks", "open-workbook collection"),
        ("Excel.Workbook", "document"),
        ("Excel.Worksheets", "typed worksheet collection"),
        ("Excel.Worksheet", "range owner"),
        ("Excel.Range", "value and formula transport boundary"),
    ] {
        output.push_str(&format!(
            "| `{id}` | Project classification: {role}. | {} | Type-library verification required before typed wrapper design; Runtime verification required before behavioral claims. |\n",
            object_evidence(objects, id)
        ));
    }
    output.push_str("\n## Canonical object-return paths\n\nOnly stored `returns` relationships appear below; absent edges are not inferred.\n\n| From | Member | To | Evidence |\n| --- | --- | --- | --- |\n");
    let desired = [
        "Excel.Application.Workbooks",
        "Excel.Application.ActiveWorkbook",
        "Excel.Workbooks.Add",
        "Excel.Workbooks.Open",
        "Excel.Workbook.Worksheets",
        "Excel.Workbook.ActiveSheet",
        "Excel.Worksheet.Range",
        "Excel.Worksheet.Cells",
        "Excel.Worksheet.UsedRange",
        "Excel.Range.Item",
        "Excel.Range.Cells",
        "Excel.Range.Rows",
        "Excel.Range.Columns",
        "Excel.Range.Offset",
        "Excel.Range.Range",
        "Excel.Range.Find",
        "Excel.Range.Worksheet",
    ];
    for member_id in desired {
        match relationships
            .iter()
            .find(|relation| relation.kind == "returns" && relation.member.as_deref() == Some(member_id))
        {
            Some(relation) => output.push_str(&format!(
                "| `{}` | `{member_id}` | `{}` | Documentation-established: stored return relationship. |\n",
                relation.from, relation.to
            )),
            None => output.push_str(&format!(
                "| -- | `{member_id}` | -- | Deferred: no canonical return relationship; Type-library verification required. |\n"
            )),
        }
    }
    output.push_str(
        "\n## Adjacent families\n\n| Family | Evidence | Treatment |\n| --- | --- | --- |\n",
    );
    for id in [
        "Excel.Sheets",
        "Excel.Windows",
        "Excel.Window",
        "Excel.Names",
        "Excel.Name",
        "Excel.ListObjects",
        "Excel.ListObject",
        "Excel.ChartObjects",
        "Excel.ChartObject",
        "Excel.Chart",
        "Excel.Shapes",
        "Excel.Shape",
    ] {
        output.push_str(&format!(
            "| `{id}` | {} | Deferred: adjacent family; Project classification: outside candidate 0.1. |\n",
            object_evidence(objects, id)
        ));
    }
    output.push_str("\n## Range capability decomposition\n\n| Capability | Candidate canonical members | Boundary |\n| --- | --- | --- |\n");
    for (capability, ids, boundary) in [
        (
            "Addressing and selection",
            "Excel.Worksheet.Range, Excel.Worksheet.Cells, Excel.Worksheet.UsedRange, Excel.Range.Item, Excel.Range.Range",
            "Documentation-established: documented member records. Project classification: selector facade is only a candidate.",
        ),
        (
            "Navigation",
            "Excel.Range.Rows, Excel.Range.Columns, Excel.Range.Offset, Excel.Range.Resize",
            "Type-library verification required for argument invocation details; Runtime verification required for shape behavior.",
        ),
        (
            "Values and formulas",
            "Excel.Range.Value, Excel.Range.Value2, Excel.Range.Formula, Excel.Range.Formula2",
            "Deferred to Prompt 04: VARIANT and SAFEARRAY transport semantics.",
        ),
        (
            "Mutation",
            "Excel.Range.ClearContents, Excel.Range.Clear, Excel.Range.Delete, Excel.Range.Copy, Excel.Range.PasteSpecial",
            "Runtime verification required for side effects and clipboard behavior.",
        ),
        (
            "Inspection and calculation",
            "Excel.Range.Address, Excel.Range.Count, Excel.Range.Find, Excel.Range.Sort",
            "Type-library verification required for optional/default arguments; Runtime verification required for results.",
        ),
    ] {
        output.push_str(&format!("| {capability} | {ids} | {boundary} |\n"));
    }
    output.push_str("\n## Knowledge-base quality findings\n\n");
    output.push_str(&format!(
        "Documentation-established: source coverage reports {} unresolved return-object references and {} unresolved review entries.\n\n",
        coverage.unresolved_return_object_references.len(),
        coverage.unresolved.len()
    ));
    output.push_str("- Project classification: collection flags are source-title evidence only; several documented collection objects are intentionally not promoted to wrapper behavior.\n- Type-library verification required: default members, `DISPID`s, invoke kinds, parameter directions/types, aliases, and enum values remain absent by design.\n- Runtime verification required: application availability, indexed lookup, enumeration, optional-argument effects, range transport, and shutdown behavior are not documentation facts.\n- Project classification: canonical JSONL and generated reports are LF-only; repository attributes preserve that invariant on Windows checkouts.\n");
    output
}

fn candidate_members(members: &[MemberRecord]) -> String {
    let mut output = heading(
        "Candidate 0.1 members",
        "Candidate scope is intentionally small and remains subject to later architecture review.",
    );
    output.push_str("## Candidate surface\n\n| Object | Candidate member | Documentation evidence | Candidate rationale and gate |\n| --- | --- | --- | --- |\n");
    let groups = [
        (
            "Excel.Application",
            &[
                "Visible",
                "Version",
                "Workbooks",
                "ActiveWorkbook",
                "ActiveSheet",
                "Calculation",
                "DisplayAlerts",
                "ScreenUpdating",
                "EnableEvents",
                "Run",
                "Quit",
            ][..],
            "root navigation and application controls",
        ),
        (
            "Excel.Workbooks",
            &["Count", "Item", "Add", "Open", "Close"][..],
            "workbook collection navigation and lifecycle",
        ),
        (
            "Excel.Workbook",
            &[
                "Name",
                "FullName",
                "Path",
                "Worksheets",
                "Save",
                "SaveAs",
                "Close",
                "Saved",
            ][..],
            "document identity, navigation, and persistence",
        ),
        (
            "Excel.Worksheets",
            &["Count", "Item", "Add"][..],
            "typed worksheet collection navigation",
        ),
        (
            "Excel.Worksheet",
            &["Name", "Range", "Cells", "UsedRange", "Activate"][..],
            "worksheet identity and range entry points",
        ),
        (
            "Excel.Range",
            &[
                "Address",
                "Value",
                "Value2",
                "Formula",
                "Formula2",
                "Rows",
                "Columns",
                "Offset",
                "Resize",
                "ClearContents",
                "Clear",
                "Delete",
                "Copy",
                "PasteSpecial",
                "Select",
                "Activate",
                "Find",
                "Sort",
            ][..],
            "range navigation, value transport, mutation, and discovery",
        ),
    ];
    for (owner, names, rationale) in groups {
        for name in names {
            let record = members.iter().find(|member| {
                member.owner == owner && member.name == *name && member.kind != "event"
            });
            let id = record
                .map(|member| member.id.as_str())
                .unwrap_or("no canonical non-event member");
            output.push_str(&format!(
                "| `{owner}` | `{id}` | {} | Project classification: candidate for {rationale}; Type-library verification required before typed/dynamic invocation design; Runtime verification required before semantics. |\n",
                record.map(member_record_evidence).unwrap_or_else(|| "Deferred: no canonical record found.".to_owned())
            ));
        }
    }
    output.push_str("\n## Explicit deferrals\n\n| Group | Status |\n| --- | --- |\n| `Sheets`, `Windows`, `Names`, `ListObjects`, `ChartObjects`, and `Shapes` | Deferred: collection and object family analysis is recorded separately; not candidate 0.1 wrappers. |\n| charts, pivots, queries, connections, add-ins, and UI families | Deferred: no public API or milestone is implied. |\n| events | Deferred: interface identity and connection-point behavior need type-library and runtime evidence. |\n");
    output
}

fn collection_analysis(
    objects: &[ObjectRecord],
    members: &[MemberRecord],
    coverage: &SourceCoverage,
) -> String {
    let mut output = heading(
        "Collection analysis",
        "This report separates source collection wording from unverified COM collection mechanics.",
    );
    output.push_str("| Collection | Documentation-established evidence | Count / Item / Add records | Project classification and required verification |\n| --- | --- | --- | --- |\n");
    for id in [
        "Excel.Workbooks",
        "Excel.Worksheets",
        "Excel.Sheets",
        "Excel.Windows",
        "Excel.Names",
        "Excel.ListObjects",
        "Excel.ChartObjects",
        "Excel.Shapes",
    ] {
        let snippets = ["Count", "Item", "Add"]
            .iter()
            .map(|name| {
                members
                    .iter()
                    .find(|member| {
                        member.owner == id && member.name == *name && member.kind != "event"
                    })
                    .map(|member| format!("`{}` ({})", member.id, member_record_evidence(member)))
                    .unwrap_or_else(|| format!("`{id}.{name}` (not retained)"))
            })
            .collect::<Vec<_>>()
            .join("<br>");
        let special = if id == "Excel.Sheets" {
            " Project classification: potentially heterogeneous sheet family; do not promise a typed item wrapper."
        } else {
            " Project classification: wrapper shape is deferred."
        };
        output.push_str(&format!(
            "| `{id}` | {} | {snippets} |{special} Type-library verification required for default member, `DISPID`, item type, and enumeration. Runtime verification required for indexing and enumeration. |\n",
            object_evidence(objects, id)
        ));
    }
    output.push_str("\n## Findings\n\n");
    output.push_str(&format!(
        "Documentation-established: the parser's title-derived collection classification is true for {} of the eight mandatory review objects; this difference is not silently repaired here.\n\n",
        objects
            .iter()
            .filter(|object| matches!(object.id.as_str(), "Excel.Workbooks" | "Excel.Worksheets" | "Excel.Sheets" | "Excel.Windows" | "Excel.Names" | "Excel.ListObjects" | "Excel.ChartObjects" | "Excel.Shapes") && object.classification.is_collection)
            .count()
    ));
    output.push_str(&format!(
        "Deferred: {} unresolved return-object references in the source coverage preclude using return-type absence as an item/default-member conclusion.\n",
        coverage.unresolved_return_object_references.len()
    ));
    output
}

fn optional_targets(members: &[MemberRecord], relationships: &[RelationshipRecord]) -> String {
    let mut output = heading(
        "Optional-argument targets",
        "Parameter order and optionality are documentation evidence; defaults and COM invocation details are not.",
    );
    output.push_str("| Member | Retained parameter order | Related enum links | Verification target |\n| --- | --- | --- | --- |\n");
    for id in [
        "Excel.Workbooks.Open",
        "Excel.Workbook.SaveAs",
        "Excel.Workbook.Close",
        "Excel.Worksheets.Add",
        "Excel.Range.Find",
        "Excel.Range.Sort",
        "Excel.Application.Run",
        "Excel.Workbook.ExportAsFixedFormat",
        "Excel.Range.ExportAsFixedFormat",
    ] {
        let Some(member) = members.iter().find(|member| member.id == id) else {
            output.push_str(&format!(
                "| `{id}` | Deferred: record absent. | -- | Type-library verification required. |\n"
            ));
            continue;
        };
        let parameters = if member.parameters.is_empty() {
            "Documentation-established: no retained parameters.".to_owned()
        } else {
            member
                .parameters
                .iter()
                .map(|parameter| {
                    format!(
                        "`{}`: {}{}",
                        parameter.name,
                        parameter.optionality,
                        parameter
                            .documented_type
                            .as_deref()
                            .map(|value| format!(" `{value}`"))
                            .unwrap_or_default()
                    )
                })
                .collect::<Vec<_>>()
                .join("; ")
        };
        let enums = relationships
            .iter()
            .filter(|relation| relation.kind == "member-references-enum" && relation.from == id)
            .map(|relation| format!("`{}`", relation.to))
            .collect::<Vec<_>>();
        output.push_str(&format!(
            "| `{id}` | Documentation-established: {parameters} | {} | Type-library verification required for parameter directions, optional/default encoding, named arguments, and invocation flags. Runtime verification required for omitted/default behavior. |\n",
            if enums.is_empty() { "No stored enum relationship.".to_owned() } else { enums.join(", ") }
        ));
    }
    output.push_str("\n## Evidence boundary\n\nDocumentation-established: the canonical schema retains parameter names, order, optionality, and selected documented types. Deferred: it does not retain full source syntax text or default values, so this report deliberately does not reconstruct them.\n");
    output
}

fn typelib_targets(members: &[MemberRecord]) -> String {
    let mut output = heading(
        "Type-library audit targets",
        "Targets define evidence to collect later; they assert no installed type-library facts.",
    );
    let candidate_count = candidate_ids()
        .iter()
        .filter(|id| members.iter().any(|member| member.id == **id))
        .count();
    output.push_str(
        "| Priority | Target set | Required audit facts | Why |\n| --- | --- | --- | --- |\n",
    );
    for (priority, targets, facts, why) in [
        (
            "1",
            "`Excel.Application` and root candidate members",
            "coclass/CLSID, interface IID, DISPIDs, invoke kinds, property/method collisions",
            "Dynamic root calls cannot be designed from documentation alone.",
        ),
        (
            "2",
            "candidate 0.1 member records",
            "parameter type, direction, optional/default encoding, return type, aliases",
            "{} current canonical candidate records require confirmation before typed wrappers.",
        ),
        (
            "3",
            "`Workbooks`, `Worksheets`, `Sheets`, `Windows`, `Names`, `ListObjects`, `ChartObjects`, `Shapes`",
            "default member, item return interface, `_NewEnum`, count type, collection interface",
            "Collection semantics are deliberately unclaimed.",
        ),
        (
            "4",
            "`Range.Value`, `Value2`, `Formula`, `Formula2`, `Find`, `Sort`, and export methods",
            "VARIANT/SAFEARRAY signatures, optional argument representation, return type",
            "Range transport and optional invocation need a separate evidence base.",
        ),
        (
            "5",
            "application/workbook/worksheet event interfaces",
            "source IID, DISPIDs, connection points, callback signatures",
            "Events are deferred and cannot be inferred from page names.",
        ),
        (
            "6",
            "adjacent chart, name, shape, table, pivot, query, and connection families",
            "interface identity, aliases, member signatures",
            "Deferred breadth; no wrapper generation is authorized.",
        ),
    ] {
        let why = if why.contains("{}") {
            why.replacen("{}", &candidate_count.to_string(), 1)
        } else {
            why.to_owned()
        };
        output.push_str(&format!(
            "| {priority} | {targets} | Type-library verification required: {facts}. | {why} |\n"
        ));
    }
    output
}

fn runtime_probes(members: &[MemberRecord]) -> String {
    let mut output = heading(
        "Runtime probe targets",
        "This is a prioritized experiment backlog only. No Excel instance is opened by the generator.",
    );
    output.push_str(
        "| Priority | Probe | Canonical member anchor | Question |\n| --- | --- | --- | --- |\n",
    );
    for (priority, probe, member, question) in [
        (
            "1",
            "Application availability",
            "Excel.Application.ActiveWorkbook",
            "What is returned with no workbook, an unsaved workbook, and a visible/hidden application?",
        ),
        (
            "1",
            "Workbook opening",
            "Excel.Workbooks.Open",
            "Which optional inputs change open behavior and error reporting?",
        ),
        (
            "1",
            "Workbook saving",
            "Excel.Workbook.SaveAs",
            "What are omitted/default argument effects and ownership/shutdown consequences?",
        ),
        (
            "1",
            "Worksheet creation",
            "Excel.Worksheets.Add",
            "What is returned and how do Before/After/index choices behave?",
        ),
        (
            "1",
            "Collection indexing",
            "Excel.Workbooks.Item",
            "Do numeric and string keys work; what is the index base and missing-item error?",
        ),
        (
            "1",
            "Collection enumeration",
            "Excel.Workbooks.Count",
            "Does enumeration exist and what are the lifetime/error behaviors?",
        ),
        (
            "1",
            "Range addressing",
            "Excel.Worksheet.Range",
            "How do A1 names, two-argument ranges, and invalid addresses map to results?",
        ),
        (
            "1",
            "Range value shape",
            "Excel.Range.Value2",
            "What VARIANT/SAFEARRAY shape represents scalar, row, column, rectangle, and multi-area reads?",
        ),
        (
            "1",
            "Formula transport",
            "Excel.Range.Formula2",
            "How are formulas, dynamic arrays, and calculation errors represented?",
        ),
        (
            "2",
            "Range mutation",
            "Excel.Range.ClearContents",
            "Which state changes occur and how are errors surfaced?",
        ),
        (
            "2",
            "Range navigation",
            "Excel.Range.Offset",
            "How do omitted offsets and resize dimensions affect returned ranges?",
        ),
        (
            "2",
            "Find state",
            "Excel.Range.Find",
            "Are omitted parameters stateful and what is the not-found result?",
        ),
        (
            "2",
            "Sort behavior",
            "Excel.Range.Sort",
            "Which optional argument combinations are accepted and persistent?",
        ),
        (
            "2",
            "Application controls",
            "Excel.Application.DisplayAlerts",
            "What restoration policy is needed after errors?",
        ),
        (
            "2",
            "Macro invocation",
            "Excel.Application.Run",
            "How are names, argument omission, and return values transported?",
        ),
        (
            "3",
            "Window and active-sheet availability",
            "Excel.Application.ActiveSheet",
            "Which document/window states produce null-like, error, or sheet-family results?",
        ),
        (
            "3",
            "Export",
            "Excel.Range.ExportAsFixedFormat",
            "What defaults, file ownership, and failure modes occur?",
        ),
        (
            "3",
            "Lifecycle",
            "Excel.Application.Quit",
            "What happens to references, unsaved state, and application ownership?",
        ),
    ] {
        let evidence = if members.iter().any(|record| record.id == member) {
            "Documentation-established: canonical record present."
        } else {
            "Deferred: canonical record absent."
        };
        output.push_str(&format!("| {priority} | {probe} | `{member}` ({evidence}) | Runtime verification required: {question} |\n"));
    }
    output
}

fn candidate_ids() -> Vec<&'static str> {
    vec![
        "Excel.Application.Visible",
        "Excel.Application.Version",
        "Excel.Application.Workbooks",
        "Excel.Application.ActiveWorkbook",
        "Excel.Application.ActiveSheet",
        "Excel.Application.Calculation",
        "Excel.Application.DisplayAlerts",
        "Excel.Application.ScreenUpdating",
        "Excel.Application.EnableEvents",
        "Excel.Application.Run",
        "Excel.Application.Quit",
        "Excel.Workbooks.Count",
        "Excel.Workbooks.Item",
        "Excel.Workbooks.Add",
        "Excel.Workbooks.Open",
        "Excel.Workbooks.Close",
        "Excel.Workbook.Name",
        "Excel.Workbook.FullName",
        "Excel.Workbook.Path",
        "Excel.Workbook.Worksheets",
        "Excel.Workbook.Save",
        "Excel.Workbook.SaveAs",
        "Excel.Workbook.Close",
        "Excel.Workbook.Saved",
        "Excel.Worksheets.Count",
        "Excel.Worksheets.Item",
        "Excel.Worksheets.Add",
        "Excel.Worksheet.Name",
        "Excel.Worksheet.Range",
        "Excel.Worksheet.Cells",
        "Excel.Worksheet.UsedRange",
        "Excel.Worksheet.Activate#method",
        "Excel.Range.Address",
        "Excel.Range.Value",
        "Excel.Range.Value2",
        "Excel.Range.Formula",
        "Excel.Range.Formula2",
        "Excel.Range.Rows",
        "Excel.Range.Columns",
        "Excel.Range.Offset",
        "Excel.Range.Resize",
        "Excel.Range.ClearContents",
        "Excel.Range.Clear",
        "Excel.Range.Delete",
        "Excel.Range.Copy",
        "Excel.Range.PasteSpecial",
        "Excel.Range.Select",
        "Excel.Range.Activate",
        "Excel.Range.Find",
        "Excel.Range.Sort",
    ]
}

fn object_evidence(objects: &[ObjectRecord], id: &str) -> String {
    objects
        .iter()
        .find(|object| object.id == id)
        .map(|object| {
            format!(
                "Documentation-established: {}; source `{}`.",
                sanitize(&object.summary),
                object.source.path
            )
        })
        .unwrap_or_else(|| "Deferred: no canonical object record found.".to_owned())
}

fn member_evidence(members: &[MemberRecord], id: &str) -> String {
    members
        .iter()
        .find(|member| member.id == id)
        .map(member_record_evidence)
        .unwrap_or_else(|| "Deferred: no canonical member record found.".to_owned())
}

fn member_record_evidence(member: &MemberRecord) -> String {
    let return_type = member
        .documented_return_type
        .as_deref()
        .unwrap_or("not retained");
    format!(
        "Documentation-established: {} {}, access `{}`, return `{}`, {} parameters; source `{}`.",
        member.kind,
        sanitize(&member.summary),
        member.access,
        return_type,
        member.parameters.len(),
        member.source.path
    )
}

fn sanitize(value: &str) -> String {
    value.replace('|', "\\|").replace(['\n', '\r'], " ")
}
