use crate::model::*;
use crate::validate;
use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedSummary {
    pub reports: usize,
}

pub fn generate_reports(root: &Path) -> Result<GeneratedSummary, String> {
    validate::validate_root(root)?;
    let reports = report_contents(root)?;
    let directory = root.join("generated");
    fs::create_dir_all(&directory)
        .map_err(|error| format!("cannot create {}: {error}", directory.display()))?;
    for (name, content) in reports {
        fs::write(directory.join(name), content)
            .map_err(|error| format!("cannot write generated report: {error}"))?;
    }
    Ok(GeneratedSummary { reports: 4 })
}

pub fn check_reports(root: &Path) -> Result<(), String> {
    let first = report_contents(root)?;
    let second = report_contents(root)?;
    if first != second {
        return Err("report generation is not deterministic".to_owned());
    }
    for (name, expected) in first {
        let path = root.join("generated").join(name);
        let actual = fs::read_to_string(&path)
            .map_err(|error| format!("cannot read generated report {}: {error}", path.display()))?;
        if actual != expected {
            return Err(format!(
                "generated report {} is stale; run generate",
                path.display()
            ));
        }
        if actual.contains("\r\n") || !actual.ends_with('\n') {
            return Err(format!(
                "generated report {} does not use deterministic LF/final-newline output",
                path.display()
            ));
        }
    }
    Ok(())
}

pub fn report_contents(root: &Path) -> Result<BTreeMap<&'static str, String>, String> {
    let (objects, members, _relationships, enums, coverage) = validate::load_records(root)?;
    let mut reports = BTreeMap::new();
    reports.insert("object-index.md", object_index(&objects, &members));
    reports.insert(
        "member-kind-summary.md",
        member_summary(&objects, &members, &enums, &coverage),
    );
    reports.insert("source-coverage.md", source_coverage(&coverage));
    reports.insert("unresolved-classification.md", unresolved(&coverage));
    Ok(reports)
}

fn object_index(objects: &[ObjectRecord], members: &[MemberRecord]) -> String {
    let mut output = String::from(
        "# Excel object index\n\nGenerated by `excel-com-kb`; do not edit by hand.\n\n| Object ID | Display name | Collection | Properties | Methods | Events | Source |\n| --- | --- | --- | ---: | ---: | ---: | --- |\n",
    );
    for object in objects {
        let count = |kind: &str| {
            members
                .iter()
                .filter(|member| member.owner == object.id && member.kind == kind)
                .count()
        };
        output.push_str(&format!(
            "| `{}` | {} | {} | {} | {} | {} | `{}` |\n",
            object.id,
            object.name,
            if object.classification.is_collection {
                "yes"
            } else {
                "no"
            },
            count("property"),
            count("method"),
            count("event"),
            object.source.path
        ));
    }
    output
}

fn member_summary(
    objects: &[ObjectRecord],
    members: &[MemberRecord],
    enums: &[EnumRecord],
    coverage: &SourceCoverage,
) -> String {
    let count = |kind: &str| members.iter().filter(|member| member.kind == kind).count();
    format!(
        "# Member-kind summary\n\nGenerated by `excel-com-kb`; documentation evidence only.\n\n| Category | Count |\n| --- | ---: |\n| Objects | {} |\n| Properties | {} |\n| Methods | {} |\n| Events | {} |\n| Enums | {} |\n| Unresolved classifications | {} |\n",
        objects.len(),
        count("property"),
        count("method"),
        count("event"),
        enums.len(),
        coverage.unresolved.len()
    )
}

fn source_coverage(coverage: &SourceCoverage) -> String {
    format!(
        "# Source coverage\n\nSource: [`{}`]({}) at commit `{}`. Counts are derived from the pinned selection in `SOURCE_MANIFEST.toml`.\n\n| Measure | Count |\n| --- | ---: |\n| Selected source files | {} |\n| Successfully parsed files | {} |\n| Skipped files | {} |\n| Files with warnings | {} |\n| Orphan records | {} |\n| Duplicate IDs | {} |\n| Unresolved owner references | {} |\n| Unresolved return-object references | {} |\n| Records missing source summaries | {} |\n| Records missing source paths | {} |\n",
        coverage.source.name,
        coverage.source.repository,
        coverage.source.commit,
        coverage.selected_files,
        coverage.parsed_files,
        coverage.skipped_files.len(),
        coverage.warnings.len(),
        coverage.orphan_records.len(),
        coverage.duplicate_ids.len(),
        coverage.unresolved_owner_references.len(),
        coverage.unresolved_return_object_references.len(),
        coverage.missing_summaries.len(),
        coverage.missing_source_paths.len()
    )
}

fn unresolved(coverage: &SourceCoverage) -> String {
    let mut output = String::from(
        "# Unresolved classification\n\nGenerated review queue. Entries are not silently promoted to type-library or runtime facts.\n\n| Category | Record | Source path | Detail |\n| --- | --- | --- | --- |\n",
    );
    if coverage.unresolved.is_empty() {
        output.push_str("| None | — | — | No unresolved classifications were emitted. |\n");
    } else {
        for issue in &coverage.unresolved {
            output.push_str(&format!(
                "| {} | {} | `{}` | {} |\n",
                issue.category,
                issue.id.as_deref().unwrap_or("—"),
                issue.path,
                issue.detail
            ));
        }
    }
    output
}
